#!/bin/sh
# shell aliases

# shorten
alias ta='tmux attach'
alias get='curl -O'
alias sp='. ~/.profile'
alias rnb='toilet --gay -t -f'
alias spr="curl -F 'sprunge=<-' http://sprunge.us"
alias ix="curl -F 'f:1=<-' ix.io"


# replace
alias vi='nvim'
alias cc='clang'
alias df='dfc'
alias top='htop'

# rlwrap
for prog in lein; do
	alias $prog="rlwrap $prog"
done

# cp
alias cp='cp -arv'

# mv
alias mv='mv -v'

# ls
alias ls='ls -F --color=auto --group-directories-first'
alias ll='ls -lhoGg'
alias la='ls -a'

# mkdir
alias mkdir='mkdir -p'

# administration
alias sudit="sudo $EDITOR"
