#!/bin/sh
# shell aliases

# shorten
alias mc="column -c 80"
alias sp=". ~/.profile"
alias ta="tmux attach"
alias get="curl -O"
alias png="ping -c 3"
alias irc="ii -s rizonbnc.us.rizon.net -k IRCPASS -p 1234 -i $IRC &"
alias ircas="ii -s irc.rizon.net -i $IRC -n"
alias rnb="toilet --gay -t -f"
alias say="echo "$@" > in"
alias byz="byzanz-record $@ desktop.gif"
alias spr="curl -F 'sprunge=<-' http://sprunge.us"
alias mkd="mkdir -p"

# games
alias oa="xinit /usr/bin/openarena -- :1"

# replace
alias vi="nvim"
alias cc="clang"
alias df="dfc"
alias top="htop"

# cp
alias cp="cp -arv"

# mv
alias mv="mv -v"

# ls
alias ls="ls -F --color=auto --group-directories-first"
alias ll="ls -lhoGg"
alias la="ls -a"
alias lc="ls | mc"

# rm
alias rdf="rm -rf"

# administration
alias sudit="sudo $EDITOR"
alias mktmp="mkdir -pm 700 $TMPDIR/$SUBTMP"

# rust
alias rsc="rustc"
