#!/bin/sh
# window mangler vars

# root for wm files
export WROOT="$TMPDIR/wm"

# group files
export WGROUPS="$WROOT/groups.d"

# each file in $WSTATUS represents a group
# if it contains 0, the group is inactive, if it contains 1, it's active.
export WSTATUS="$WROOT/status.d"

# wm vars (panel height, gaps, border width, number of groups)
export WMCONF="$HOME/local/wm/conf"
